apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-host
  namespace: keycloak
data:
  keycloak-internal-host: keycloak.keycloak
  keycloak-internal-url: http://keycloak.keycloak
  keycloak-external-host: iam.soil.mosip.net
  keycloak-external-url: https://iam.soil.mosip.net 
  keycloak-internal-service-url: http://keycloak.keycloak/auth/
