istio:
  name: postgres
  host: postgres.sandbox.xyz.net
  ingressController: <istio-ingressgateway>
  port:
    name: postgres
    number: 5432
    protocol: TCP
  serviceHost: postgres-postgresql
  servicePort: 5432
